### ISSUE TITLE
Link issue-some projects are not exactly linked

### ISSUE THREAD

**Issue by merinpriyasha** [TharshanSM/TharshanSM.github.io#8]
![Capture01](https://user-images.githubusercontent.com/68733175/148887645-39315824-c3ac-4103-ae71-bcacdfcafccc.PNG)

* In this page COVID App and EDU BOT projects are not exactly linked with any other code or site to launch it. 
* If you have not yet completed above projects, it would be nice if you could add a text or message (ex: Still under developing) to let the web user know.

**Comment by TharshanSM** [comment]
some projects are not in GitHub. I will add a link after pushing it to the GitHub

**Comment by merinpriyasha** [comment]
yes it's okay. 👍

**Comment by merinpriyasha** [comment]
> some projects are not in GitHub. I will add a link after pushing it to the GitHub

yes it's okay. 👍 you can change it future after you link those projects.

**Comment by TharshanSM** [comment]
I update sources file except the last one because its still under developing
